name: Unit Testing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXTERNAL_API: https://fakepage.com
      API_KEY: fakeKey

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Verify Docker installation
        run: docker --version

      - name: List Docker containers
        run: docker ps -a

      - name: Install dependencies
        run: npm ci

      - name: Echo EXTERNAL_API
        run: echo $EXTERNAL_API

      - name: Run unit tests
        run: npm run test
